# Generated by Django 4.1.4 on 2023-02-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_name',
            new_name='profile_user',
        ),
    ]
